baseurl: "/"
title: "Universal"
params:
  logo: 'logo.svg'
  primary_color: "#3eb2fd"
menus:
  main:
    - identifier: home
      weight: 1
      url: index.html
      title: Home
    - identifier: features
      weight: 2
      url: features.html
      title: Features
sass:
  input_file: sass/main.scss.njk
  output_file: assets/css/main.css
  indentWidth: 4
  outputStyle: nested
  precision: 10
